name: AH1
version: 1.0
main: com.civilgamers.ah1.base.AH1
load: startup
commands:
  goto:
    description: goto player
  ah:
    description: contains gamemode commands
  advert:
    description: adverts a message globally
  example:
    description: test